version: '3.8'

services:

  jenkins-with-node:
    image: vonot16/jenkins-with-node-configured
    user: root
    ports:
      - "8080:8080"
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db

  api:
    build:
      context: .
      dockerfile: ./api/Dockerfile
    container_name: lista-de-tarefas-api
    ports:
      - "50000:8080"
    environment:
      MONGO_URL: mongodb://mongodb:27017
      MONGO_USER: root
      MONGO_PASS: root
    depends_on:
      - mongodb

  web-application:
    image: edrassimoes/dockerfile-aplicacao:1.0
    container_name: lista-de-tarefas
    ports:
      - "3000:3000"