# Define a versão da sintaxe do Docker Compose que está sendo utilizada no arquivo.
version: '3.8'
# https://github.com/docker/awesome-compose/tree/master/react-express-mongodb
services:

  jenkins-with-node:
    build:
      context: ./docker
      dockerfile: Dockerfile-jenkins
    container_name: jenkins
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins_compose/jenkins_configuration:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - ./data:/data/db

  web-application:
    build:
      context: .
      dockerfile: Dockerfile-aplicacao
    container_name: lista-de-tarefas
    ports:
      - "3000:3000"