# Usa uma imagem base do Jenkins
FROM jenkins/jenkins:latest

# Instala o Node.js
USER root
RUN apt-get update
RUN apt-get install -y ca-certificates curl gnupg
RUN mkdir -p /etc/apt/keyrings
RUN curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg
ARG NODE_MAJOR=20
RUN echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | tee /etc/apt/sources.list.d/nodesource.list
RUN apt-get update
RUN apt-get install nodejs -y

# Instalado mailutils
RUN apt-get install mailutils

# Altera o usuário de volta para o Jenkins
USER jenkins

# docker build -t jenkins-with-node .
# docker run -p 8080:8080 jenkins-with-node