name: TypeScript Actions

on:
  push:
    branches: [ 'main' ]
  pull_request:
    branches: [ 'main' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm i

      - name: Running tests
        run: npm test

      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-de-testes
          path: html

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm i

      - name: Node build
        run: npm run build

      - name: Artifact upload
        uses: actions/upload-artifact@v3
        with:
          name: lista-de-tarefas
          path: dist

  notificacao:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
        run: npm i

      - name: Sanding an e-mail
        run: | 
          node nodemailer/sendEmail.js
        env:
          EMAIL: lista.de.tarefas.s107@gmail.com